### ISSUE TITLE
Crash adding macro

### ISSUE THREAD

**Issue by TheFantasticWarrior** [WarmUpTill/SceneSwitcher#1173]
**Describe the bug**
Crash when creating second macro

**To Reproduce**
1. install through by editing [aur](https://aur.archlinux.org/packages/obs-advanced-scene-switcher) pkgbuild to 1.27(also happens with manually copying files from release page)
2. obs->tools->advanced scene switcher
3. add 2 macros
4. segmentation fault after clicking ok on name menu

**Logs**
logs has no useful information, gdb output below
```
info: [adv-ss] started
[New Thread 0x7fff7fe006c0 (LWP 602774)]
[Thread 0x7fff9e4006c0 (LWP 602769) exited]
info: [adv-ss] curl loaded successfully
info: [adv-ss] found curl library
warning: QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,0'

Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
0x00007ffff3593889 in QObject::deleteLater() () from /usr/lib/libQt6Core.so.6
(gdb) bt
#0  0x00007ffff3593889 in QObject::deleteLater() () from /usr/lib/libQt6Core.so.6
#1  0x00007fffc13e3691 in advss::AdvSceneSwitcher::on_macroAdd_clicked (this=0x555557b653b0)
    at /usr/src/debug/obs-advanced-scene-switcher/obs-advanced-scene-switcher/lib/macro/macro-tab.cpp:103
#2  0x00007fffc12d0542 in advss::AdvSceneSwitcher::qt_metacall (this=0x555557b653b0, 
    _c=QMetaObject::InvokeMetaMethod, _id=35, _a=0x7fffffffc420)
    at /usr/src/debug/obs-advanced-scene-switcher/build/advanced-scene-switcher-lib_autogen/ZJOKMXDKB7/moc_advanced-scene-switcher.cpp:1632
#3  0x00007ffff35a1784 in ?? () from /usr/lib/libQt6Core.so.6
#4  0x00007ffff460e24b in ?? () from /usr/lib/libQt6Widgets.so.6
#5  0x00007ffff460e748 in ?? () from /usr/lib/libQt6Widgets.so.6
#6  0x00007ffff461b12e in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
   from /usr/lib/libQt6Widgets.so.6
#7  0x00007ffff4743aed in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt6Widgets.so.6
#8  0x00007ffff454c15e in QWidget::event(QEvent*) () from /usr/lib/libQt6Widgets.so.6
#9  0x00007ffff44fc51c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt6Widgets.so.6
#10 0x00007ffff45019c1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#11 0x00007ffff3544d28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt6Core.so.6
#12 0x00007ffff44f3e2d in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt6Widgets.so.6
#13 0x00007ffff4561fb2 in ?? () from /usr/lib/libQt6Widgets.so.6
#14 0x00007ffff45635f0 in ?? () from /usr/lib/libQt6Widgets.so.6
#15 0x00007ffff44fc51c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt6Widgets.so.6
#16 0x00007ffff3544d28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt6Core.so.6
#17 0x00007ffff3b76df0 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt6Gui.so.6
#18 0x00007ffff3be5d64 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Gui.so.6
#19 0x00007fffe1d58637 in ?? () from /usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#20 0x00007ffff1b0eab9 in ?? () from /usr/lib/libglib-2.0.so.0
#21 0x00007ffff1b709e7 in ?? () from /usr/lib/libglib-2.0.so.0
#22 0x00007ffff1b0dfc5 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#23 0x00007ffff37a2cbd in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt6Core.so.6
#24 0x00007ffff354f01e in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt6Core.so.6
#25 0x00007ffff354934d in QCoreApplication::exec() () from /usr/lib/libQt6Core.so.6
#26 0x00005555555f1cff in main ()
(gdb) up 1
#1  0x00007fffc13e3691 in advss::AdvSceneSwitcher::on_macroAdd_clicked (this=0x555557b653b0)
    at /usr/src/debug/obs-advanced-scene-switcher/obs-advanced-scene-switcher/lib/macro/macro-tab.cpp:103
103		addPulse->deleteLater();
(gdb) l
98		if (!AddNewMacro(newMacro, name)) {
99			return;
100		}
101	
102		ui->macros->Add(newMacro);
103		addPulse->deleteLater();
104		addPulse = nullptr;
105		emit MacroAdded(QString::fromStdString(name));
106	}
107	
```
**Version information**
 - OS: [e.g. Windows 10] Arch Linux
 - Kernel Version: Linux 6.10.3-arch1-2
 - OBS Version [e.g. 27.1.3] 30.2.1-1
 - Plugin Version [e.g. 1.17.1]1.27.0

**Comment by WarmUpTill** [comment]
Thanks for the reporting the issue and especially including a backtrace!
Seems like this bug has hidden in the code for a while and I found a few more problematic instances of this issue.

To be honest I am a bit surprised that this issue does not seem to happen on the other platforms for some reason.

I will release an official fix later today.
If you want to work around the problem you can _disable_ this setting on the General tab on reboot OBS:

![grafik](https://github.com/user-attachments/assets/2778dc28-a7ab-4bd2-92ca-267384447f54)
